language: python
python:
  - "2.7"
#  - "2.6"

virtualenv:
  system_site_packages: true

before_install: sudo apt-get update

install:
 - sudo apt-get install
    python-pypoker-eval
    python-libxml2
    python-libxslt1
    mysql-server
    libmysql++-dev
    memcached
    libssl-dev
    libmysqlclient-dev
    gettext
    libmcrypt-dev
    bc
    apg
    php5-cli
 - pip install -U pip
 - pip install
    http://pypi.python.org/packages/source/w/wstools/wstools-0.4.tar.gz
    http://pypi.python.org/packages/source/f/fpconst/fpconst-0.7.2.tar.gz
    http://pypi.python.org/packages/source/z/zope.interface/zope.interface-4.0.1.tar.gz
    http://pypi.python.org/packages/source/T/Twisted/Twisted-11.1.0.tar.bz2
    http://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-1.2.3.tar.gz
    http://ftp.tummy.com/pub/python-memcached/python-memcached-1.51.tar.gz
    http://pypi.python.org/packages/source/s/simplejson/simplejson-2.6.1.tar.gz
    http://pypi.python.org/packages/source/c/coverage/coverage-3.5.2.tar.gz
    http://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.tar.gz
    http://pypi.python.org/packages/source/p/pyasn1/pyasn1-0.1.4.tar.gz
    http://pypi.python.org/packages/source/S/SOAPpy/SOAPpy-0.12.5.tar.gz
    http://pypi.python.org/packages/source/p/python-cjson/python-cjson-1.0.5.tar.gz
    http://pypi.python.org/packages/source/p/pyOpenSSL/pyOpenSSL-0.13.tar.gz
    http://pypi.python.org/packages/source/m/msgpack-python/msgpack-python-0.4.0.tar.gz
    git+git://github.com/pokermania/pokerdistutils.git#egg=poker-distutils
    git+git://github.com/pokermania/reflogging.git#egg=reflogging
    git+git://github.com/pokermania/pokerengine.git#egg=poker-engine
    git+git://github.com/pokermania/pokerpackets.git#egg=poker-packets

# command to run tests, e.g. python setup.py test
before_script:
 - ln -s $(readlink -f pokernetwork) $(readlink -f ${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages)/pokernetwork
 - mysqladmin -u root password 123
 - python setup.py configure -s pokernetwork.paths.src=$(readlink -f ${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages)/pokernetwork
 - python setup.py configure -s pokernetwork.paths.conf=$(readlink -f ${VIRTUAL_ENV})/share/poker-network/conf
 - python setup.py configure -s pokernetwork.paths.data=$(readlink -f ${VIRTUAL_ENV})/share/poker-network
 - python setup.py configure -s pokerengine.paths.src=$(readlink -f ${VIRTUAL_ENV}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/pokerengine)
 - python setup.py configure -s pokerengine.paths.conf=$(readlink -f ${VIRTUAL_ENV}/share/poker-engine/conf)
 - python setup.py configure -s pokerengine.paths.data=$(readlink -f ${VIRTUAL_ENV}/share/poker-engine)
 - python setup.py configure -s test.engine_path=$(readlink -f ${VIRTUAL_ENV}/share/poker-engine)
 - python setup.py build
script: PYTHON_PATH=$(readlink -f .) python setup.py test
