language: python
python:
  - "2.7"
#  - "2.6"

virtualenv:
  system_site_packages: true

before_install: sudo apt-get update -qq

install:
 - sudo apt-get install -qq python-pypoker-eval
 - sudo apt-get install -qq python-cjson
 - sudo apt-get install -qq python-libxml2
 - sudo apt-get install -qq python-libxslt1
 - sudo apt-get install -qq mysql-server
 - sudo apt-get install -qq libmysql++-dev
 - sudo apt-get install -qq memcached
 - sudo apt-get install -qq libtool
 - sudo apt-get install -qq libssl-dev
 - sudo apt-get install -qq rsync
 - sudo apt-get install -qq libmysqlclient-dev
 - sudo apt-get install -qq gettext
 - sudo apt-get install -qq apg
 - sudo apt-get install -qq libmcrypt-dev
 - sudo apt-get install -qq bc
 - pip install http://github.com/pokermania/pokerdistutils/archive/master.zip
 - pip install http://github.com/pokermania/reflogging/archive/master.zip
 - pip install http://github.com/pokermania/pokerengine/archive/master.zip
 - pip install http://github.com/pokermania/pokerpackets/archive/master.zip

# command to run tests, e.g. python setup.py test
before_script: python setup.py build
script: PYTHON_PATH=$(readlink -f .) python setup.py test
